### ISSUE TITLE
Error when setting requester_name to full name on the webform

### ISSUE THREAD

**Issue by kkumaren** [strakers/zendesk-drupal-webform#30]
**Describe the bug**
Error when setting requester_name to full name on the webform.

**To Reproduce**
1. Go to webform Emails/Handlers settings
2. Click on Edit
3. Select full name in the requester field
4. Save the settings
5. Go to the webform and submit the form

**Expected behavior**

**Screenshots**
![Screenshot from 2019-12-17 21-10-07](https://user-images.githubusercontent.com/6490158/71199114-b5ebba00-22ae-11ea-98a4-e325050fcc84.png)

**Comment by strakers** [comment]
Hi @kkumaren, apologies for getting back to you so late on this. Thanks so much for reporting this, and I'll open a new branch to look into this issue.

**Comment by strakers** [comment]
Hi @kkumaren, thanks again. I reviewed your pull request and I see where the addition of the check for string was necessary. I also noticed a need to check to ensure that when the name is in array format, all the expected fields are present. For this reason I created a polyfill class to handle this. 

I've created the pull request and will be reviewing this.

**Comment by strakers** [comment]
Resolved in [v1.1.0](https://github.com/strakers/zendesk-drupal-webform/releases/v1.1.0)
