### ISSUE TITLE
Full configuration and successful submit does not create new ticket.

### ISSUE THREAD

**Issue by gsilva-swapp** [strakers/zendesk-drupal-webform#46]
**Describe the bug**
I'm trying to create tickets from my web application (Local instance) and even when I got a successfull message for submitting the webform the ticket is not creating on zendesk client aplication.

**To Reproduce**
1. Get a Zendesk API Key
2. Activate the Module
3. Configure the Zendesk Connection Settings
4. Add a Zendesk Handler to a Webform
![image](https://user-images.githubusercontent.com/92805693/153883709-b856b05e-6bef-430b-b0dd-39720ae98a5d.png)
5. Sumbit the webform
![image](https://user-images.githubusercontent.com/92805693/153884352-41e3f16c-4810-4561-acbf-ec583a6327ba.png)

**Expected behavior**
We need that the webform sumbit create a new ticket.
![image](https://user-images.githubusercontent.com/92805693/153877165-2f8dd6ab-8eb2-46ac-af9a-ad6cabb3f6c2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome

**Comment by gsilva-swapp** [comment]
The Zendesk Connection Settings was the real issue. On [https://www.drupal.org/project/webform_zendesk] there is an example image that explain how to set the parameters, however, the Zendesk Url on Drupal 9 must be **_without_** '.zendesk.com' to get the correct functioning of the module.

**Comment by strakers** [comment]
> The Zendesk Connection Settings was the real issue. On [https://www.drupal.org/project/webform_zendesk] there is an example image that explain how to set the parameters, however, the Zendesk Url on Drupal 9 must be **_without_** '.zendesk.com' to get the correct functioning of the module.

Hi @gsilva-swapp , that's a different package that you referenced, but I do appreciate the feedback. On the next release, I'll make more clear the format for entering in the configuration. 

If you find any other issues, please feel free to submit another issue and I'll respond as soon as I can.
